apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app5
spec:
  type: ClusterIP
  selector:
    app: spring-boot-app5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090  # Map Kubernetes service to container's port 9090
